[FEAT] 상품 주문하기 기능 구현
tjdgh925/MarketProject pull request #21
Opened 2022-08-05 16:11 UTC by tjdgh925

2022-08-09 06:31 UTC, dongKos requested changes
테스트 코드 아주 잘 짰습니다 굳! 
다음번에 여유가 된다면 통합테스트도 작성해보면 좋겠네요 😄

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/domain/item/repository/ItemRepositoryImpl.java
>                  .where(item.member.eq(member))
BooleanExpression이라는 키워드로 찾아봐서 where 조건에 들어갈 값들을 넣는 새로운 방식에 대해서 고민을 해보시면 좋을 것 같습니다. 지금처럼 조건이 하나라면 코드를 보는데 문제가 없겠지만, 조건이 많아질 수록 가독성이 떨어질 수 있습니다 😄

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/domain/item/repository/ItemRepositoryImpl.java
> +        Long size = queryFactory.select(item.count())
size를 구하는 count쿼리를 먼저 실행하는 방식은 어떨까요? size가 0으로 나온다면 그 다음 select하는 쿼리는 안해도 되겠죠? 성능에 조금이라도 도움이 된다면 고민해볼 가치가 있을 것 같네요 😄

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/domain/item/service/ItemService.java
> +            throw new Exception(ErrorCode.NOT_ENOUGH_STOCK.getMessage() + "(현재 재고 수량" + item.getStockNumber() + ")");
findItemById 에서는 BusinessException으로 예외포장을 하는데 여기서는 그냥 Exception을 던지는 이유가 있을까요?

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +public class ItemDtlController {
Resource를 내려주는 controller와 redirect 목적의 controller로 분리하는게 좋아보이네요 😄

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +        try {
각 controller method마다 예외처리를 해주는 것은 효율적인 객체지향 프로그래밍이라고 보기 어려운 부분이 있습니다.
@ExceptionHandler, @RestControllerAdvice 등의 키워드를 참고해서 예외를 공통으로 처리하는 부분을 추가해보면 좋을 것 같습니다 😄

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/service/ItemDtlService.java
> +@Transactional(readOnly = true)
@Transactional은 모든 method에 공통으로 적용할게 아니라면 클래스 선언부에 선언하는건 지양했으면 합니다

2022-08-09 06:31 UTC, dongKos commented on src/main/java/com/project/market/web/main/controller/MainController.java
> +        Pageable pageable = PageRequest.of(page.isPresent() ? page.get() : 0, 6);
여기 사용된 0, 6 같은 숫자들은 상수화하면 좋을 것 같네요. 코드를 처음보거나 오랜만에 본다면 이해하기 어려울 수 있겠네요 😢

2022-08-09 08:36 UTC, tjdgh925 commented on src/main/java/com/project/market/domain/item/service/ItemService.java
> +            throw new Exception(ErrorCode.NOT_ENOUGH_STOCK.getMessage() + "(현재 재고 수량" + item.getStockNumber() + ")");
BusinessException과 달리 오류 메시지 내부에 상품의 재고 수량을 변수로 받아서 출력하려고 Exception을 사용했습니다.

2022-08-09 09:03 UTC, dongKos commented on src/main/java/com/project/market/domain/item/service/ItemService.java
> +            throw new Exception(ErrorCode.NOT_ENOUGH_STOCK.getMessage() + "(현재 재고 수량" + item.getStockNumber() + ")");
그렇다면 기존 ErrorCode를 동적으로 errormessage를 할당해서 사용할 수 있도록 변경하거나 새로운 ErrorCode를 정의해서 사용하는게 좋겠네요! 그냥 Exception을 던지는것은 의미를 유추하기가 어렵기 때문에 지양하는게 좋다고 생각합니다 😄

2022-08-09 11:06 UTC, tjdgh925 commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +        try {
@ExceptionHandler 로 처리해보려 했지만, BindingResult를 parameter 값으로 받아올 때 오류가 생겨서 ResponseEntity 값을 반환해주는 Controller에만 적용해 보겠습니다

2022-08-09 11:20 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +        try {
비즈니스 로직 안에서 처리하려고 하지 말고, 에러 처리 라는 책임만을 담당하는 클래스를 따로 만들어서 처리하면 어떨까요? 그러면 비즈니스 로직에서는 특정 경우에 throw new BusinessException(ErrorCode.??) 만 해주면 될거고, try-catch 로직이 들어갈 필요가 없겠죠??

```
@ControllerAdvice
public class ControllerExceptionHandler {
  @ExceptionHandler(BusinessException.class)
  public ResponseEntity handleBusinessException() {
    return new ResponseEntity(HttpStatus.BAD_REQUEST);
  }
}
```

2022-08-09 11:23 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +        try {
추가로 저 handleBusinessException 메소드의 리턴타입은 커스텀하게 정의할 수 있습니다. 그냥 ResponseEntity가 아니라요. 저걸 ErrorResponse 같은 커스텀 객체로 만들어서 처리해보는것도 좋겠네요 😄

2022-08-11 15:11 UTC, dongKos requested changes
고생하셨습니다! 마이너한 몇가지만 더 수정하면 좋겠네요 😄

2022-08-11 15:11 UTC, dongKos commented on src/main/java/com/project/market/domain/item/repository/ItemRepositoryImpl.java
> +                    .where(item.itemSellStatus.eq(ItemSellStatus.SELL)
그냥 조건과 BooleanExpression 이 같이 있습니다. 통일을 하면 가독성이 더 좋겠네요 😄 
BooleanExpression여러개가 있을 경우 
`where(eqItemSearch(),eqOther(), ...)`
이런식으로 표현 할 수 있습니다.

2022-08-11 15:11 UTC, dongKos commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +@ControllerAdvice
RestController에서 발생한 에러를 처리하는 곳은 없는건가요? StockException이 발생했을때는 어떻게 처리가 되는걸까요? 그리고 에러를 공통으로 처리하는 부분에서는 에러 상황에 대한 로깅이나 stackTrace를 찍어줘야겠죠?

2022-08-12 02:10 UTC, dongKos requested changes
마지막 수정 사항이 되겠네요 👍

2022-08-12 02:10 UTC, dongKos commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +@RestControllerAdvice
이렇게 하면 그냥 Controller도 처리를 같이 할수가 없겠죠?
`@RestControllerAdvice(annotations = RestController.class)`

이런식으로 처리하면 둘 다 커버할 수 있습니다 😄

2022-08-12 06:21 UTC, tjdgh925 commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +@RestControllerAdvice
감사합니다 ㅎㅎ 해당 사항 수정하고 머지 할게요

2022-08-12 06:35 UTC, dongKos commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +@RestControllerAdvice
요 부분은 제가 잘못 알고 있었네요. 저도 리뷰 하면서 하나 배웠습니다.

@ControllerAdvice -> 모든 @RestController, @Controller 어노테이션 아래에서 발생한 예외 처리
@RestControllerAdvice -> 모든 @RestController, @Controller 어노테이션 아래에서 발생한 예외 처리 + 리턴타입을 json 형태로 만들어줌

따라서, 
@RestControllerAdvice, @ControllerAdvice 둘 다 사용해도 상관 없습니다. 리턴타입을 어떻게 내려줄것이냐에 따라 다르겠네요. 다만 이 프로젝트는 model attribute를 내려주는 곳도 있기 때문에 @ControllerAdvice가 적절해 보입니다 😄

2022-08-12 06:35 UTC, dongKos commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +@RestControllerAdvice
요부분만 수정해서 머지 하시면 될것 같습니다!

2022-08-12 06:55 UTC, merged