[FEAT] 장바구니 기능 구현
tjdgh925/MarketProject pull request #23
Opened 2022-08-12 08:10 UTC by tjdgh925

2022-08-13 07:40 UTC, dongKos requested changes
고생하셨습니다! 코멘트 확인 하시고 수정 부탁드립니다!

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/domain/cart/entity/Cart.java
> +    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
nit: Cascade가 all로 되어있으면 cart가 삭제 됐을때 orderItem도 지워지지 않나요? 도메인 구조를 잘 몰라서 질문 드립니다

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/domain/cart/service/CartService.java
> +    @Transactional
readOnly역할을 하는 서비스의 경우 
@Transactional(readOnly=true)로 명시를 해주도록 합시다 😄

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/domain/cart/service/CartService.java
> +    @Transactional
공동 작업 하는 사람들을 위해서 입니다

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/domain/item/entity/Item.java
> +           if (this.stockNumber > 0 && this.itemSellStatus == ItemSellStatus.SOLD_OUT){
클린코드 연습중 하나인데, `this.stockNumber > 0 && this.itemSellStatus == ItemSellStatus.SOLD_OUT` 같은 조건을 메소드로 추출해서 네이밍으로 의미를 전달하는 방식도 있습니다. 연습해보세요

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/domain/order/entity/Order.java
> +        orderItem.setCart(null);
OrderItem의 Cart 필드에 기본값을 null로 넣어놓으면 여기는 필요없지 않을까요?

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +    @ExceptionHandler(EntityNotFoundException.class)
모든 exception이 처리로직이 동일하고 응답코드만 다르다면 Exception타입으로 받아서 한 메소드에서만 처리하면 어떨까 합니다. code만 달라지는거면 if절 안에서 instanceof로 처리하거나 Enum을 만드는것도 좋겠네요

```
@ExceptionHandler(Exception.class)
public ResponseEntity handle(Exception exception) {
  log.error();
  
  int code = 0;
  if(exception instanceof DtoEmptyException)
    code = HttpStatus.BAD_REQUEST;
  ...
}
```

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/cartList/dto/CartListItemDto.java
> +@Setter
Setter는 어디서 사용하나요?

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/cartList/controller/CartListRestController.java
> +    @PatchMapping("/orderItem/{id}")
patch 👍

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/cartList/dto/CartOrderDto.java
> +@Setter
이 setter도 확인 해주세요

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/cartList/service/CartListService.java
> +    @Transactional
read만 하는 곳은 마찬가지로 readOnly를 붙여줍시다 😄

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/cartList/service/CartListService.java
> +            item.reduceStock(count-before);
stock은 마이너스값이 될 수 있는건가요?

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/cartList/service/CartListService.java
> +                throw new StockException(item.getStockNumber());
[early return pattern](https://gomjellie.github.io/%ED%8C%A8%ED%84%B4/2020/04/27/early-return.html)을 사용해서 리팩토링 하면 좋겠네요 😄

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +        try {
이제 우리는 RestControllerAdvice가 있으니 try catch는 필요없을 것 같습니다. 예외가 발생할 수 있는곳에서 예외를 포장해서 발생시키도록 합시다.

2022-08-13 07:40 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/service/ItemDtlService.java
> +@Transactional(readOnly = true)
공통 @Transactional은 지양하는걸로!

2022-08-13 07:42 UTC, dongKos commented
pr 분리 필요..

2022-08-16 07:23 UTC, tjdgh925 commented on src/main/java/com/project/market/domain/cart/entity/Cart.java
> +    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
장바구니가 지워지면 장바구니에 있는 orderItem들도 지우기 위해서 ALL로 지정했습니다.

2022-08-16 07:25 UTC, tjdgh925 commented on src/main/java/com/project/market/domain/order/entity/Order.java
> +        orderItem.setCart(null);
이 부분은 장바구니에 있는 제품을 주문할 경우에 장바구니 정보를 초기화 하기 위해서 메소드를 추가했습니다.

2022-08-16 10:39 UTC, dongKos requested changes
고생하셨습니다! 수정 안된 부분이 몇가지가 있네요 확인 부탁드립니다 😄

2022-08-16 10:39 UTC, dongKos commented on src/main/java/com/project/market/domain/item/entity/Item.java
> +           if (isStockChanged()){
인덴트의 상태가?!

2022-08-16 10:39 UTC, dongKos commented on src/main/java/com/project/market/global/error/exception/ControllerExceptionHandler.java
> +        if (exception instanceof BusinessException) {
어..음.. enum으로 해보면 어떨까요? if else 코드 되게 가독성이 안좋네요

2022-08-16 10:39 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/controller/ItemDtlController.java
> +        try {
요건 아직 수정 안된거죠?

2022-08-16 10:39 UTC, dongKos commented on src/main/java/com/project/market/web/itemdtl/service/ItemDtlService.java
> +@Transactional(readOnly = true)
요것도 수정이 안된 것 같네요

2022-08-16 13:47 UTC, merged