[FEAT] 주문 이력 조회 기능 구현
tjdgh925/MarketProject pull request #25
Opened 2022-08-18 03:57 UTC by tjdgh925

2022-08-18 11:44 UTC, dongKos requested changes
고생하셨습니다! join하는 부분에 의문이 있어서 코멘트 남겼습니다! 합당한 이유가 있다면 코멘트 달아주세요~

2022-08-18 11:44 UTC, dongKos commented on src/main/java/com/project/market/domain/order/repository/OrderRepositoryImpl.java
> +            orderHistDto.setTotalPrice(getTotalPrice(orderHistDto.getOrderId()));
join을 사용하지 않고 이렇게 한 이유가 있을까요?

2022-08-18 11:44 UTC, dongKos commented on src/main/java/com/project/market/domain/order/repository/OrderRepositoryImpl.java
> +        return JPAExpressions.select(itemImage.imageUrl)
요거도 상품아이디로 join하면 되지 않을까요?

2022-08-19 06:46 UTC, tjdgh925 commented on src/main/java/com/project/market/domain/order/repository/OrderRepositoryImpl.java
> +            orderHistDto.setTotalPrice(getTotalPrice(orderHistDto.getOrderId()));
join을 사용해서 서브쿼리를 사용해서 하나의 쿼리를 사용하려 했는데, 하나 이상의 결과 값을 반환한다는 오류 때문에 이렇게 따로 처리했습니다.

2022-08-24 11:32 UTC, merged