[FEAT] 주문 취소 기능 구현
tjdgh925/MarketProject pull request #28
Opened 2022-08-24 11:33 UTC by tjdgh925

2022-08-24 12:31 UTC, dongKos requested changes
고생하셨습다! 코멘트 몇개남겼어요 😄

2022-08-24 12:31 UTC, dongKos commented on src/main/java/com/project/market/domain/order/service/OrderService.java
> +        List<OrderItem> orderItems = order.getOrderItems();
OrderItem 엔티티 쪽으로 빼는건 어때요?

2022-08-24 12:31 UTC, dongKos commented on src/main/java/com/project/market/domain/order/service/OrderService.java
> +        List<OrderItem> orderItems = order.getOrderItems();
완전 DDD 스타일로!

2022-08-24 12:31 UTC, dongKos commented on src/test/java/com/project/market/web/orderhist/service/OrderHistServiceTest.java
>  class OrderHistServiceTest {
원래 통합테스트는 안하고 있었죠?

2022-08-24 12:33 UTC, dongKos commented on src/main/java/com/project/market/web/orderhist/controller/OrderHistRestController.java
> +    public ResponseEntity cancelOrder(@PathVariable Long orderId) {
cancelOrder는 리턴이 없네요? 뭔가 사용자에게 즉각적으로 반응이 되는건아닌건가요? 만약 그렇다면 도메인 이벤트로 전환해서 연습해보는 것도 좋겠네요. 물론 실시간성이 아니라는 전재에요

2022-08-25 12:08 UTC, tjdgh925 commented on src/test/java/com/project/market/web/orderhist/service/OrderHistServiceTest.java
>  class OrderHistServiceTest {
네네 단위 테스트만 진행하고 있습니다

2022-08-26 09:11 UTC, dongKos approved these changes
LGTM 👍

2022-08-26 09:11 UTC, dongKos commented on src/main/java/com/project/market/global/config/listener/OrderCancelListener.java
> +    public void onApplicationEvent(OrderCancelEvent event) {
오오 좋습니다!! 
현업에서는 보통 [이런방식](https://sunghs.tistory.com/139)을 사용해요 😄 이미 구현한건 요렇게 두고 다음번 이벤트 부터는 다르게 해보시죠! 대용량 및 비동기 처리를 구현해봅시다 다음번에는!

2022-08-26 09:11 UTC, dongKos commented on src/test/java/com/project/market/web/orderhist/service/OrderHistServiceTest.java
>  class OrderHistServiceTest {
다음번에 TestContainer 이용해서 통합테스트 작성해보면 어떨까요? 관련 내용은 지원 해드릴게요

2022-08-26 11:53 UTC, merged