[FEAT] Redis와 JwtToken 환경설정
tjdgh925/MarketProject pull request #31
Opened 2022-08-26 12:30 UTC by tjdgh925

2022-08-26 13:55 UTC, dongKos requested changes
고생하셨습니다! 아직 관련 기능이 완성 된건 아닌가 보네요!

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/redis/RedisConfig.java
> +        return new LettuceConnectionFactory(redisHost, redisPort);
Lettuce 굳! jedis는 성능 이슈 때문에 안쓰는게 좋아요 😄 
나중에 왜 lettuce를 썼냐고 하면 그에 대한 답변이 되겠군요

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .antMatchers("/login", "/register", "/", "images/**", "/api/form/**").permitAll() //누구나 접근 가능
img/, /images는 무슨 차이인가요?

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +//            .and()
여긴 왜 주석된건가요? 주석 코드는 웬만하면 남기지 맙시다

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        } catch (Exception e) {
Jwt Token 만료 시, 혹은 유효하지 않은 Jwt인경우 등 토큰 관련한 많은 Exception들이 있을거에요. 그걸 뭉뚱그려서 Exception 하나로 처리하는것보다 각 Exception 별로 정의 해주면 어떨까요?

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +            if (StringUtils.isNotEmpty(token) && tokenProvider.validateToken(token)) {
StringUtils.isNotEmpty(token) 조건이 중복 되는거 같습니다

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +            Collections.unmodifiableList(
이건 어디에서 쓰나요?

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        } catch (Exception e) {
accessToken이 만료된 경우 refreshToken을 조회해서 재발급 시켜준다던지 혹은 jwt token이 만료됐다는 에러만 뱉어서 클라이언트에서 처리하게 할건지 등.. 정책적으로 고민해보고 코드를 작성해주세요!

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +                .setExpiration(expirationTime)                      // 토큰 만료 시간
refresh token에 claim을 뺀것은 아주 좋습니다 👍

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +//        catch (ExpiredJwtException e) {
아 지금 보니 validation 관련 로직이 여기에 다 있군요?? 여기 저기 try-catch가 있으니 코드를 읽기가 힘들군요 😢

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/TokenType.java
> +        return TokenType.ACCESS.name().equals(tokenType);
이건 어디서 쓰나요? accessToken인지 체크해야하는 이유가 있을까요?

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/redis/RedisConfig.java
> +        redisTemplate.setValueSerializer(new StringRedisSerializer());
redis에 key-value 형식으로 refreshToken을 저장할텐데, 데이터 구조는 어떻게 가져갈건가요?

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
spring security의 세션 생성 정책에 대해 공부해보면 아주 좋습니다 👍

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
한줄한줄 꼼꼼히!

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        String bearerToken = request.getHeader("Authorization");
불변 값들은 상수화해서 관리해주세요 🙏

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        if (StringUtils.isNotEmpty(bearerToken) && bearerToken.startsWith("Bearer ")) {
조건의 함수화!

2022-08-26 13:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +    @Value("${token.access-token-expiration-time}")
혹시 모르니 default값을 넣어줘도 좋겠네요. 이렇게만 하면 만약 application.yml에 property가 없을 경우 어플리케이션이 동작하지 않아요

2022-08-26 13:56 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        } catch (Exception e) {
이거 밑에 로직 있는거 못봤어요 ㅎㅎ 여기다가 로직 추가하지 않으셔도 됩니다!

2022-08-26 13:57 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        String bearerToken = request.getHeader("Authorization");
옛날에 이거 오타났던걸로 좀 삽질을 한 기억이 있네요 😭

2022-08-28 12:16 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +            Collections.unmodifiableList(
나중에 로그인 혹은 회원가입 같이 토큰 인증이 필요하지 않은 예외 URL을 처리하기 위해서 만들어 두었습니다.

2022-08-28 12:22 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .antMatchers("/login", "/register", "/", "images/**", "/api/form/**").permitAll() //누구나 접근 가능
프로젝트 내부에 img/ 하위에 있는 정적 파일이 없어서 img 부분은 빼도 괜찮을 것 같습니다

2022-08-28 12:28 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/redis/RedisConfig.java
> +        redisTemplate.setValueSerializer(new StringRedisSerializer());
email을 key값으로 하고, refreshToken을 value 값으로 저장하려 합니다

2022-08-28 12:33 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +//            .and()
네 이전 formLogin 부분을 처리하기 위한 부분을 주석한건데 주석처리 한 부분 삭제하겠습니다

2022-08-28 12:36 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +//        catch (ExpiredJwtException e) {
다른 방법으로 처리할 수 있는 좋은 방법이 있을까요??

2022-08-28 13:04 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +            Collections.unmodifiableList(
그런 애들은 security config에 추가하면 되지 않을까요? ignore되면 filter를 안탈거에요 😄

2022-08-28 13:04 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +//        catch (ExpiredJwtException e) {
`JwtAuthenticateFilter` 에 있는 try-catch를 제거 하고 여기서 throw하는 방식으로 처리해보면 어떨까요?

2022-08-30 06:18 UTC, dongKos approved these changes
LGTM 👍

2022-08-30 06:18 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +        if (tokenValidate(token)) {
`validateToken(token)` 으로 네이밍하면 어떨까요?

2022-08-30 07:23 UTC, merged