[FEAT] Form 로그인 API 구현
tjdgh925/MarketProject pull request #35
Opened 2022-08-31 12:41 UTC by tjdgh925

2022-09-01 14:15 UTC, dongKos requested changes
고생하셨습니다! 근데 저번 pr의 코드가 섞여있는것 같네요;;

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/api/login/form/controller/FormLoginController.java
> +    @PostMapping(value = "/login", produces = MediaType.APPLICATION_JSON_VALUE)
RestController면 produces 설정 필요없지 않나요?

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/api/login/form/controller/FormLoginController.java
> +        TokenDto result = formLoginService.formLogin(formLoginDto);
굳이 필요없는 변수는 안만들면 좋겠네요!

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/global/config/redis/RedisService.java
> +public class RedisService {
음 이건 redisService라기보단 redisRepository같네요. 분리를 하거나 네이밍을 바꿔주셔요

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/global/config/redis/RedisService.java
> +public class RedisService {
분리를 추천합니다. 리프레시 토큰 관련 비즈니스 로직만 있진 않을테니깐요

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .antMatchers("/login", "/register", "/", "images/**", "/api/register", "/api/login").permitAll() //누구나 접근 가능
중복되니깐 아스터리스크로 처리해주세요

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +        String refreshToken = createRefreshToken(member.getEmail(), createRefreshTokenExpireTime());
이것도 함수 네이밍이 괜찮아서 변수는 필요없을 것 같아요!

2022-09-01 14:15 UTC, dongKos commented on src/main/java/com/project/market/api/login/form/service/FormLoginService.java
> +    public TokenDto formLogin(FormLoginRequestDto formLoginDto){
saveRefreshToken이 있으니 @transactional 있어야 할 것 같아요

2022-09-01 14:16 UTC, dongKos commented on src/main/java/com/project/market/global/config/redis/RedisService.java
> +public class RedisService {
service의 메소드 네이밍으로 어떤 비즈니스 로직을 처리하는지 명시해주고 repository에서 get 혹은 set 하면 되겠네요 😄

2022-09-01 14:34 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .antMatchers("/login", "/register", "/", "images/**", "/api/register", "/api/login").permitAll() //누구나 접근 가능
로그인이나 회원가입 이외의 API ex) "/api/order" 등의 API의 경우에는 권한이 필요해서 이렇게 처리했는데 처리할 수 있는 좋은 방법이 있을까요?

2022-09-01 14:40 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
> +                .antMatchers("/login", "/register", "/", "images/**", "/api/register", "/api/login").permitAll() //누구나 접근 가능
로그인 회워가입만 말씀드린겁니다 😄

2022-09-02 05:58 UTC, dongKos approved these changes
LGTM 👍

2022-09-02 06:09 UTC, merged