[FEAT] 회원정보 Api 구현
tjdgh925/MarketProject pull request #41
Opened 2022-09-19 11:48 UTC by tjdgh925

2022-09-20 06:58 UTC, dongKos requested changes
고생하셨습니다! 코멘트 확인 부탁드려요. 추가적으로 2가지정도 제안 드리려고 합니다.
1. pr description에 간략한 설명을 적어주면 좋겠습니다. pr template 이라는 키워드로 좀 찾아보면 github에서 제공하는 템플릿들 있어요 
2. 슬슬 통합테스트를 작성해보면 좋겠습니다.

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/api/profile/controller/ProfileApiController.java
> +        new ProfileUpdateValidator().validate(profileUpdateDto, errors);
`ProfileUpdateValidator` 를 bean으로 등록해놓고 사용하면 어떨까요? 요청 들어올때마다 객체를 생성하는건 안좋은것 같아요

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/api/profile/controller/ProfileApiController.java
> +    public ResponseEntity getEmail(@RequestHeader("Authorization") String bearerToken) {
상수 어때요?

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/api/profile/service/ProfileApiService.java
> +        return bearerToken.substring("Bearer ".length());
정.상.수

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
>                  .antMatchers("/admin/**", "/api/admin/**").hasRole("ADMIN")
admin, /api/admin 은 무슨 차이인가요?

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +                Authentication authentication = tokenProvider.getAuthentication(token);
`getAuthenticaton`에서는 예외처리를 안해주나요? 발생시점에서 처리해주는게 맞는것 같아요

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +    protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
오호 이런 신박한 기능이?

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +    public boolean isTokenExpired(String token) {
제가 알기론 `validateToken` 메소드에 태우면 만료된것도 체크해주는걸로 알고있는데 아닌가요? 아니라면 죄송하고, 만약 맞다면 catch를 2개로 나눠서 잡아주세용

2022-09-20 06:58 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +    public boolean isTokenExpired(String token) {
테스트 해보시고 말씀해주세요

2022-09-20 12:04 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/SecurityConfig.java
>                  .antMatchers("/admin/**", "/api/admin/**").hasRole("ADMIN")
이 부분도 login과 register처럼 묶어서 처리하겠습니다

2022-09-20 12:06 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +    protected boolean shouldNotFilter(HttpServletRequest request) throws ServletException {
jwtFilter가 springSecurity의 UsernamePasswordAuthenticationFilter보다 먼저 적용되어서 따로 jwtFilter에서 처리해주었습니다

2022-09-20 14:00 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +                Authentication authentication = tokenProvider.getAuthentication(token);
어디서 예외처리를 해야한다는건지 잘 이해를 못 했어요

2022-09-22 14:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +                Authentication authentication = tokenProvider.getAuthentication(token);
`tokenProvider.getAuthentication(token)` 안에서 예외처리를 해줘야 한다는 뜻!

2022-09-22 14:55 UTC, dongKos commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +    public boolean isTokenExpired(String token) {
요건 확인 혹은 수정된건가요?

2022-09-22 14:56 UTC, dongKos reviewed
코멘트 남긴거 확인 부탁드립니다~

2022-09-22 17:03 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/jwt/JwtTokenProvider.java
> +    public boolean isTokenExpired(String token) {
원래는 만료된것은 확인이 안되는 것이 맞았는데, validateToken 메소드 내에서 만료 시간까지 수정할 수 있도록 수정했습니다.

2022-09-22 17:08 UTC, tjdgh925 commented on src/main/java/com/project/market/global/config/security/jwt/JwtAuthenticateFilter.java
> +                Authentication authentication = tokenProvider.getAuthentication(token);
getAuthentication 메서드 내부의 userDetailsService.loadUserByUsername 메서드에서 회원이 없을 경우에 대한 예외처리를 해주는데, 추가로 다른 예외처리도 해야 한다는 건가요??

2022-09-24 02:32 UTC, dongKos approved these changes

2022-09-24 06:26 UTC, merged